version: '3.4'

services:
  apigateway:
    image: ${DOCKER_REGISTRY-}apigateway
    build:
      context: .
      dockerfile: Gateways/ApiGateway/Dockerfile
    depends_on:
      - equipmentmicroservice

  authmicroservice:
    image: ${DOCKER_REGISTRY-}authmicroservice
    build:
      context: .
      dockerfile: Microservices/AuthMicroservice/Dockerfile

  equipmentmicroservice:
    image: ${DOCKER_REGISTRY-}equipmentmicroservice
    build:
      context: .
      dockerfile: Microservices/EquipmentMicroservice/Dockerfile
